networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  traefik_proxy:
    name: traefik_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

include:
  - ./compose/docker-compose-socket-proxy.yml
  - ./compose/docker-compose-traefik-local.yml
  - ./compose/docker-compose-postgres.yml
  - ./compose/docker-compose-pgadmin.yml
  - ./compose/docker-compose-redis.yml
  - ./compose/docker-compose-mosquitto.yml
  - ./compose/docker-compose-influxdb.yml
  - ./compose/docker-compose-telegraf.yml
  - ./compose/docker-compose-authentik.yml
  - ./compose/docker-compose-uns-builder.yml
  - ./compose/docker-compose-spb-sim.yml
  - ./compose/docker-compose-sie-sim.yml
  - ./compose/docker-compose-zavia-apps.yml
