persistence true
persistence_location /var/lib/mosquitto/
log_dest stdout

allow_anonymous false

auth_plugin /mosquitto/go-auth.so
auth_opt_backends postgres
auth_opt_log_level info
auth_opt_exhaust_backend_first true

auth_opt_pg_host postgres
auth_opt_pg_port 5432
auth_opt_pg_dbname zavia
auth_opt_pg_user zavia
auth_opt_pg_password change_this_postgres_password
auth_opt_pg_sslmode disable
auth_opt_pg_connect_tries -1

auth_opt_pg_userquery SELECT password_hash FROM mqtt_clients WHERE username = $1 AND is_active = true LIMIT 1
auth_opt_pg_superquery SELECT COUNT(*) FROM mqtt_clients WHERE username = $1 AND is_admin = true AND is_active = true
auth_opt_pg_aclquery SELECT a.topic FROM mqtt_client_acls a INNER JOIN mqtt_clients c ON c.id = a.client_id WHERE c.username = $1 AND c.is_active = true AND ((a.rw = 1 AND $2 IN (1,4)) OR (a.rw = 2 AND $2 = 2) OR (a.rw = 3 AND $2 IN (1,2,4)))

listener 1883

listener 8883
certfile /etc/mosquitto/certs/zavia_wildcard.crt
keyfile /etc/mosquitto/certs/zavia_wildcard.key

listener 9001
protocol websockets
