services:
  uns-builder:
    build:
      context: ${UNS_BUILDER_CONTEXT:-../../uns_builder}
      dockerfile: Dockerfile
      network: host
    restart: unless-stopped
    container_name: zavia-uns-builder
    profiles: ["apps", "all"]
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started
    command: uvicorn main:app --app-dir /app/src --host 0.0.0.0 --port 8000 --reload --proxy-headers --forwarded-allow-ips='*'
    networks:
      - traefik_proxy
      - default
    environment:
      - ENV=development
      - UVICORN_RELOAD=true
      - SSL_CERT_FILE=/etc/ssl/certs/zavia_rootCA.pem
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/zavia_rootCA.pem
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - mqtt_broker=mosquitto
      - mqtt_port=1883
      - mqtt_username=${UNS_MQTT_USERNAME}
      - mqtt_password=${UNS_MQTT_PASSWORD}
      - mqtt_client_id=${UNS_MQTT_CLIENT_ID}
      - mqtt_tls_enabled=${UNS_MQTT_TLS_ENABLED}
      - mqtt_will_topic=${UNS_MQTT_WILL_TOPIC}
      - mqtt_will_payload=${UNS_MQTT_WILL_PAYLOAD}
      - OIDC_CLIENT_ID=${UNS_OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${UNS_OIDC_CLIENT_SECRET}
      - OIDC_ISSUER_URL=https://auth.zavia.lan/application/o/uns/
      - OIDC_VERIFY_TLS=true
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_INIT_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_INIT_BUCKET}
    volumes:
      - ${UNS_BUILDER_CONTEXT:-../../uns_builder}/backend/src:/app/src
      - ../../local_certs/out/zavia_rootCA.pem:/etc/ssl/certs/zavia_rootCA.pem:ro
    ports:
      - "${UNS_BUILDER_HOST_PORT:-8000}:8000"
    labels:
      - traefik.enable=true
      # HTTP Routers
      - traefik.http.routers.uns-rtr-http.entrypoints=web
      - traefik.http.routers.uns-rtr-http.rule=Host(`uns.${DOMAINNAME_1}`)
      - traefik.http.routers.uns-rtr-http.service=uns-svc
      - traefik.http.routers.uns-rtr.entrypoints=websecure
      - traefik.http.routers.uns-rtr.rule=Host(`uns.${DOMAINNAME_1}`)
      - traefik.http.routers.uns-rtr.tls=true
      # Services
      - traefik.http.routers.uns-rtr.service=uns-svc
      - traefik.http.services.uns-svc.loadbalancer.server.port=8000
      #middleware chain
      - "traefik.http.routers.uns-rtr.middlewares=middlewares-secure-headers@file"
      - "traefik.http.routers.uns-rtr-http.middlewares=middlewares-secure-headers@file"
