services:
  uns-builder:
    build:
      context: ../../uns_builder
      dockerfile: Dockerfile
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - traefik_proxy
      - default
    environment:
      - ENV=development
      - UVICORN_RELOAD=true
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - mqtt_broker=mosquitto
      - mqtt_port=1883
      - mqtt_username=${UNS_MQTT_USERNAME}
      - mqtt_password=${UNS_MQTT_PASSWORD}
      - mqtt_client_id=${UNS_MQTT_CLIENT_ID}
      - mqtt_tls_enabled=${UNS_MQTT_TLS_ENABLED}
      - mqtt_will_topic=${UNS_MQTT_WILL_TOPIC}
      - mqtt_will_payload=${UNS_MQTT_WILL_PAYLOAD}
    volumes:
      - ../../uns_builder/app/src:/app/src:ro
    ports:
      - "${UNS_BUILDER_HOST_PORT:-8000}:8000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.uns-rtr-http.entrypoints=web
      - traefik.http.routers.uns-rtr-http.rule=Host(`uns.${DOMAINNAME_1}`)
      - traefik.http.routers.uns-rtr-http.service=uns-svc
      - traefik.http.routers.uns-rtr.entrypoints=websecure
      - traefik.http.routers.uns-rtr.rule=Host(`uns.${DOMAINNAME_1}`)
      - traefik.http.routers.uns-rtr.tls=true
      - traefik.http.routers.uns-rtr.service=uns-svc
      - traefik.http.services.uns-svc.loadbalancer.server.port=8000
