services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: zavia-redis
    profiles: ["core", "all"]
    networks:
      - default
      - traefik_proxy
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${DOCKERDIR}/appdata/redis/data:/data
    labels:
      - traefik.enable=false
