services:
  mosquitto:
    image: iegomez/mosquitto-go-auth:latest
    restart: unless-stopped
    container_name: zavia-mosquitto
    profiles: ["core", "broker", "apps", "all"]
    networks:
      - traefik_proxy
      - default
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - TZ=${TZ}
    volumes:
      - ${DOCKERDIR}/logs/mosquitto:/var/log/mosquitto
      - ${DOCKERDIR}/appdata/mosquitto/data:/var/lib/mosquitto
      - ${DOCKERDIR}/appdata/mosquitto/config:/etc/mosquitto
      - ${DOCKERDIR}/appdata/traefik/certs/zavia_wildcard.crt:/etc/mosquitto/certs/zavia_wildcard.crt:ro
      - ${DOCKERDIR}/appdata/traefik/certs/zavia_wildcard.key:/etc/mosquitto/certs/zavia_wildcard.key:ro
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.mqtt-rtr.entrypoints=mqtt
      - traefik.tcp.routers.mqtt-rtr.rule=HostSNI(`*`)
      - traefik.tcp.routers.mqtt-rtr.service=mqtt-svc
      - traefik.tcp.services.mqtt-svc.loadbalancer.server.port=1883
      - traefik.tcp.routers.mqtt-secure-rtr.entrypoints=mqtt-secure
      - traefik.tcp.routers.mqtt-secure-rtr.rule=HostSNI(`*`)
      - traefik.tcp.routers.mqtt-secure-rtr.tls.passthrough=true
      - traefik.tcp.routers.mqtt-secure-rtr.service=mqtt-secure-svc
      - traefik.tcp.services.mqtt-secure-svc.loadbalancer.server.port=8883
