services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    restart: unless-stopped
    container_name: zavia-socket-proxy
    profiles: ["core", "all"]
    security_opt:
      - no-new-privileges:true
    environment:
      - CONTAINERS=1
      - SERVICES=1
      - TASKS=1
      - NETWORKS=1
      - POST=0
      - INFO=1
      - IMAGES=1
      - PING=1
      - VERSION=1
      - EVENTS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket_proxy
