services:
  telegraf:
    image: telegraf:alpine
    restart: unless-stopped
    container_name: zavia-telegraf
    profiles: ["monitoring", "all"]
    networks:
      - default
    depends_on:
      - influxdb
    volumes:
      - ${DOCKERDIR}/appdata/telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf:rw
