services:
  traefik:
    image: traefik:3.3
    restart: unless-stopped
    profiles: ["core", "all"]
    depends_on:
      - socket-proxy
    security_opt:
      - no-new-privileges:true
    networks:
      traefik_proxy:
        ipv4_address: 192.168.90.254
      socket_proxy:
    command:
      - --api=true
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.endpoint=tcp://socket-proxy:2375
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik_proxy
      - --providers.file.directory=/rules
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.traefik.address=:8080
      - --entrypoints.mqtt.address=:1883
      - --entrypoints.mqtt-secure.address=:8883
      - --log=true
      - --log.level=INFO
      - --accesslog=true
    ports:
      - "${TRAEFIK_HTTP_PORT}:80"
      - "${TRAEFIK_HTTPS_PORT}:443"
      - "${TRAEFIK_DASHBOARD_PORT}:8080"
      - "${MQTT_PORT}:1883"
      - "${MQTT_SECURE_PORT}:8883"
    volumes:
      - ${DOCKERDIR}/appdata/traefik/config:/rules
      - ${DOCKERDIR}/logs/traefik:/logs
    environment:
      - TZ=${TZ}
      - DOMAINNAME_1=${DOMAINNAME_1}
      - LOCAL_IPS=${LOCAL_IPS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-api-rtr-http.entrypoints=web
      - traefik.http.routers.traefik-api-rtr-http.rule=(Host(`traefik.${DOMAINNAME_1}`) || Host(`${DOMAINNAME_1}`)) && PathPrefix(`/api`)
      - traefik.http.routers.traefik-api-rtr-http.service=api@internal
      - traefik.http.routers.traefik-dashboard-rtr-http.entrypoints=web
      - traefik.http.routers.traefik-dashboard-rtr-http.rule=(Host(`traefik.${DOMAINNAME_1}`) || Host(`${DOMAINNAME_1}`)) && PathPrefix(`/dashboard`)
      - traefik.http.routers.traefik-dashboard-rtr-http.service=dashboard@internal
      - traefik.http.routers.traefik-dashboard-rtr-http.middlewares=dashboard_stripprefix@internal
      - traefik.http.routers.traefik-api-rtr.entrypoints=websecure
      - traefik.http.routers.traefik-api-rtr.rule=(Host(`traefik.${DOMAINNAME_1}`) || Host(`${DOMAINNAME_1}`)) && PathPrefix(`/api`)
      - traefik.http.routers.traefik-api-rtr.tls=true
      - traefik.http.routers.traefik-api-rtr.service=api@internal
      - traefik.http.routers.traefik-dashboard-rtr.entrypoints=websecure
      - traefik.http.routers.traefik-dashboard-rtr.rule=(Host(`traefik.${DOMAINNAME_1}`) || Host(`${DOMAINNAME_1}`)) && PathPrefix(`/dashboard`)
      - traefik.http.routers.traefik-dashboard-rtr.tls=true
      - traefik.http.routers.traefik-dashboard-rtr.service=dashboard@internal
      - traefik.http.routers.traefik-dashboard-rtr.middlewares=dashboard_stripprefix@internal
